### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by savijaysalem** [X00TD/android_kernel_asus_sdm660#2]
1.dual 4g issue (jio & vodafone)
2.notification led only support 2 colors but most of the roms are support multiple colors(battery light) 
3.auto-rotate issue (ex : open settings and then wait 10 sec without any action (landscape mode) ,automatically struck auto-rotate , one more example if you play video player 10 sec automatically struck auto-rotate(landscape mode) .turn off and on it works again but will face same problem again 
4.battery optimization

**Comment by ShivamKumarJha** [comment]
1) Known issue, wait for fix.
2) LED hardware supports only red & green for us.
3) Known minor issue. Nothing we can do about it as of now. & it takes 2-3 seconds not 10 :D
4) Battery is fine totally. Multiple confirmations.

Lastly these aren't kernel issues :P
